version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/newsdb
      NEWS_INGEST_API_KEY: super-secret-key
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
